
---
- name: install python2
  raw: sudo apt-get -y install python-simplejson

- name: install aptitude
  raw: sudo apt-get -y install aptitude

- name: apt-get | apt-get update
  apt: update_cache=yes cache_valid_time=3600
  sudo: true

- name: apt-get | ensure core packages are installed
  apt: pkg={{ item }} state=installed
  sudo: true
  with_items:
    - atool
    - atop
    - htop
    - curl
    - git
    - make
    - mc
    - python-software-properties
    - supervisor
    - tig
    - tree
    - vim
    - unzip


- name: Upgrade Server
  apt: upgrade=full
